ALTER TABLE _user RENAME TO users;
ALTER TABLE role RENAME TO roles;
ALTER TABLE users_roles ADD PRIMARY KEY (user_id, role_id);
CREATE INDEX users_roles_user on users_roles(role_id);

DROP TABLE student CASCADE;

CREATE TABLE shop_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value      VARCHAR(255),
    status     SMALLINT,
    owner_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_shop_items PRIMARY KEY (id)
);

CREATE INDEX shop_items_owner on shop_items(owner_id);

ALTER TABLE shop_items
    ADD CONSTRAINT FK_SHOP_ITEMS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE users_roles
    DROP CONSTRAINT fk_userol_on_user;

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;